version: '2'
exclude_patterns:
  - 'docs'
  - 'documentation'
  - 'dist'
  - '**/*.log'
  - '**/*.ico'
  - 'e2e/'
  - 'demo/assets/'
  - 'demo/typings.d.ts'
  - '**/*.spec.ts'
  - '**/karma.conf.js'
  - 'demo/polyfills.ts'
  - 'demo/test.ts'
