dist: trusty
sudo: false

language: node_js
node_js:
  - '10'

branches:
  only:
    - master
    - develop
    - /^greenkeeper/.*$/


before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

cache:
  directories:
    - ./node_modules

install:
  - pushd $TRAVIS_BUILD_DIR
  - npm install

script:
  - npm run build

notifications:
  email:
    recipients:
      - ibrahimwickama@wickerlabs.com
      - yusuph.wickama@wickerlabs.com
    on_failure: always
    on_success: always
